<?php
/**
 * @var $this Pys_ExtendedFilter_Block_Widget_Container
 */
?>
<?php echo $this->getBeforeScripts() ?>

<div class="content-header">
    <?php echo $this->getHeaderHtml() ?>
    <p class="buttons"><?php echo $this->getButtonsHtml('header') ?></p>
</div>

<?php echo $this->getChildHtml('', true, true); ?>

<?php if ($this->hasFooterButtons()): ?>
    <div class="content-footer">
        <p class="buttons"><?php echo $this->getButtonsHtml('footer') ?></p>
    </div>
<?php endif; ?>

<?php echo $this->getAfterScripts() ?>
